# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servicios.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fservicios.proto\x12\x04test\"8\n\x08Producto\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\"\x18\n\tRespuesta\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2D\n\tProveedor\x12\x37\n\x14SuministrarProductos\x12\x0e.test.Producto\x1a\x0f.test.RespuestaB!Z\x1fgithub.com/example/path/gen;genb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicios_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037github.com/example/path/gen;gen'
  _PRODUCTO._serialized_start=25
  _PRODUCTO._serialized_end=81
  _RESPUESTA._serialized_start=83
  _RESPUESTA._serialized_end=107
  _PROVEEDOR._serialized_start=109
  _PROVEEDOR._serialized_end=177
# @@protoc_insertion_point(module_scope)
